### ISSUE TITLE
Linking mode - navigation

### ISSUE THREAD

**Issue by sanderha** [guru-digital/silverstripe-all-in-one-page#1]
Hello, 

How can i update the "current" page in the top menu, when scrolling down the page? There is already functionality which updates the url correctly, I just need some similar functionality to update the top menu. 

Any ideas?

Otherwise awesome module.

Thanks

**Comment by cjsewell** [comment]
Hey Sanderha, 

It should already? [These lines](https://github.com/guru-digital/silverstripe-all-in-one-page/blob/master/javascript/src/AllInOnePage.js#L124-L125) add the [anchorActiveClass](https://github.com/guru-digital/silverstripe-all-in-one-page/blob/master/javascript/src/AllInOnePage.js#L18) which default to `active current` to any links that contain the pages URL.

Have you got a demo I can take a look at where it is not working?

**Comment by sanderha** [comment]
Ah I see, I forgot to add "primary" to my nav element. Thanks for the help!
